name: Deploy Vite site to GitHub Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
        
      - name: Build
        working-directory: ./frontend
        run: |
          npm run build > build_log.txt 2>&1 || (git config user.name "LogBot" && git config user.email "bot@ci.local" && git add build_log.txt && git commit -m "push log" && git push && exit 1)
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './frontend/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
